{
 "title": "HW 22",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 8 },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 13 },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk READ per instance [bytes/sec]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 22 },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}